### ISSUE TITLE
UX: Optimización del Home

### ISSUE THREAD

**Issue by Vixx-X** [jaimeni/front-solocarro#100]
Se cambió la forma en la que se actualiza el Home, para que sea más rápido según mis pruebas más de la mitad del tiempo

**Comment by Vixx-X** [comment]
@jaimeni cierra este issue si no se necesita mejorar la velocidad del home

**Comment by jaimeni** [comment]
@Vixx-X se puede ver porque Comprar Por Tipo de Servicio carga lento en el Home y Lo Esencial Para tu Vehiculo carga rapido?
