### ISSUE TITLE
Revision Checkout

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#105]
- [x] Añadir Envio
- [x] Añadir Impuesto
- [x] Añadir Total
- [x] Quitar Costo de Tienda

![image](https://user-images.githubusercontent.com/74719300/142897707-caa1c224-5081-4086-91d1-75b0c448de0f.png)

- [x] Al momento de F5/refrescar sale el mensaje de que el carrito esta vacio
- [x] Al momento de cambiar la cantidad a cero, sale la siguiente vista
![image](https://user-images.githubusercontent.com/74719300/142898025-03209ef1-e7d5-46b1-870f-057b353be702.png)

- [x] Revisar porque aparece el parachoque en 0 al ingresar a la pasarela de pago pero el precio correcto si sale en el icono

![image](https://user-images.githubusercontent.com/74719300/142898791-c6a9236d-4bf4-4b68-b2b2-ddf363f673eb.png)

![image](https://user-images.githubusercontent.com/74719300/142898855-3124428e-4c2a-445b-8bd2-86dfbaed1acb.png)

- [x] El boton Volver al carrito tiene un tiempo de respuesta mas lento que Proceder al Pago
![image](https://user-images.githubusercontent.com/74719300/142899067-23dd1721-3785-4eb3-a9aa-8e4204f8edbb.png)

- [x] El boton de Seguir Comprando tiene un lag al momento de ser cliqueado

**Comment by ronikode** [comment]
@yhau1989 validar que si llega al carrito primero coloque cantidad 1 por default no permita ir en negativo (front). Y back @Vixx-X verificar la respuesta de lo que menciona @jaimeni sobre el refresh.
