### ISSUE TITLE
UX (Servicios): Accordion servicios

### ISSUE THREAD

**Issue by yhau1989** [jaimeni/front-solocarro#113]
En base al acordeon del home (mobile), replicar funcionalidad en la **página de detalle de servicios**

**Comment by jaimeni** [comment]
@yhau1989 te refieres a la pagina detalle producto?

**Comment by jaimeni** [comment]
@yhau1989 te refieres a la vista detalle de producto?  No veo ningun acordeon en la vista detalle servicio
