### ISSUE TITLE
Flujo de recuperarar contraseña

### ISSUE THREAD

**Issue by yhau1989** [jaimeni/front-solocarro#114]
Añadir aquí la lista de task que se necesitan para que el flujo de recuperar contraseña funcione:

- Back
- Front
  - Seguir línea de diseño 
- Email
- Funcionalidad
  - los liks deben caducar por uso y por tiempo de vida (en el front debe aparecer los mensajes que muestre cada caso de uso para esto)

**Comment by yhau1989** [comment]
@jaimeni  por favor revisar esta funcionalidad cuando @Vixx-X termine

**Comment by jaimeni** [comment]
@Vixx-X Hay que traducir esta parte a español

![image](https://user-images.githubusercontent.com/74719300/143382890-b02dcede-b58f-440c-b673-3ad8cd955dbf.png)

Su contraseña ha sido cambiado exitosamente.  Por favor ingresar nuevamente con su nueva clave.
