### ISSUE TITLE
Vista - Tienda

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#121]
Cuando el usuario selecciona la Tienda de vista detalle de producto o de lista de productos, la pagina lo llevara a la pagina de la tienda.  La pagina consiste en un header donde se coloca un banner y un icono de la tienda

![image](https://user-images.githubusercontent.com/74719300/143391458-7fe22aeb-9a42-429d-a0ff-92487c1f9d43.png)

Luego se colocan los productos de la tienda.  Esto sera igual que la vista de lista de productos pero restringido a los productos de la tienda que seleccionamos.

Esta vista reemplazaria las vistas que aparecen en el Figma de la tienda.

**Comment by jaimeni** [comment]
@yhau1989 ya las APIs estan listas para hacer la vista.

**Comment by Vixx-X** [comment]
Link de la doc de los endpoints:
https://stage.workshop-garage.tech/api/docs/redoc/#tag/stores

**Comment by yhau1989** [comment]
phat: https://next.workshop-garage.tech/shops/slug-tienda

**Comment by jaimeni** [comment]
@darwinrq como accedo la vista de una tienda?  Intente las direcciones:

https://next.workshop-garage.tech/shops/tienda-1
https://next.workshop-garage.tech/shops/tienda

y todos me salen un error 404 que no existen.

**Comment by jaimeni** [comment]
@darwinrq he intentado tratar de abrir la pagina de una tienda con los siguientes links y ninguno funciona:

https://next.workshop-garage.tech/shops/tienda
https://next.workshop-garage.tech/shops/tienda
https://next.workshop-garage.tech/tienda/tienda
https://next.workshop-garage.tech/tiendas/tienda

Por favor indicar cual es el link correcto?

**Comment by jaimeni** [comment]
El link correcto es 
https://next.workshop-garage.tech/stores/korea-parts
