### ISSUE TITLE
Agregar notificaciones genericas para acciones de usuario

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#150]
Se pueden agregar notificaciones para las siguientes acciones:

- [x] agregar producto al carrito
- [x] eliminar carro del garaje
- [x] agregar carro al garaje
- [x] agregar kilometraje del carro
- [x] agregar servicio del carro

**Comment by darwinrq** [comment]
para poder utilizar la notificación :

usar la función llamada sendAlert, con los parametros (type:(success, danger, info, warning), title, message)
![Captura de pantalla de 2021-12-03 12-05-38](https://user-images.githubusercontent.com/54091814/144644688-47a89b52-8bed-4f0e-a099-cbd7227f931c.png)
![Captura de pantalla de 2021-12-03 12-06-40](https://user-images.githubusercontent.com/54091814/144644700-beee0c1a-3e6f-4607-a9be-e9affb0fb312.png)
