### ISSUE TITLE
No mostrar boton de Comprar Otra Vez si no hay inventario

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#151]
En la vista de Mis Ordenes, no mostrar el boton de Comprar Otra Vez si no hay inventario.

**Comment by yhau1989** [comment]
Como se después del cambio:

![Screen Shot 2021-12-03 at 01 49 53](https://user-images.githubusercontent.com/12787927/144558284-d349a3d1-0eee-41fb-9ab9-c2b594b686b8.png)
