### ISSUE TITLE
Arreglos UX - Vista Home

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#31]
- [x] Falta agregar una imagen de fondo al filtro del carro.

- [x] Agregar 1,2,3 en Marca, Modelo y Año a los campos del filtro del carro.

Este es el Figma
![image](https://user-images.githubusercontent.com/74719300/141437291-60f30a2b-ac97-4d25-a8ff-9fd099917f8f.png)

Este es el Home actual
![image](https://user-images.githubusercontent.com/74719300/141436694-01aa10b3-4f0c-460d-8e3f-7267c9b7dd8a.png)

- [x] Cambiar la fuente del Home para que concuerde con la del Figma

Este es el Figma
![image](https://user-images.githubusercontent.com/74719300/141437769-aecacc25-583c-4e21-84f0-fc70ec6a5d2f.png)

Este es el Home Actual
![image](https://user-images.githubusercontent.com/74719300/141437866-cecb0e2f-2b31-4c6b-8450-0d2c8857d6c6.png)

- [x] Arreglar tamaño de icono de Marcas en el Home
Este es el Figma
![image](https://user-images.githubusercontent.com/74719300/141438976-bbe237ba-7124-4bf7-8018-660dc863a86c.png)

- [x] Ajustar los colores de la pagina y fuente de texto para que concuerden con los del Figma

Este es el Figma
![image](https://user-images.githubusercontent.com/74719300/141440430-d21152f3-689b-417f-b793-7b13659ad02b.png)

![image](https://user-images.githubusercontent.com/74719300/141476400-473414f0-835c-4f87-a9c2-7427d28105cf.png)

Este es el Home
![image](https://user-images.githubusercontent.com/74719300/141440525-c86b38df-9124-48f2-8cb7-ff0805f3e7db.png)

![image](https://user-images.githubusercontent.com/74719300/141476439-9268ff43-b364-4032-b16f-10ffe8d9dd16.png)

**Comment by yhau1989** [comment]
Cómo se ve antes del cambio
![Titulo Front Sol](https://user-images.githubusercontent.com/12787927/142046315-953e453a-772a-41cb-9d89-79d5e63b5594.png)

**Comment by yhau1989** [comment]
Después del cambio:
![Titulo Front Sol](https://user-images.githubusercontent.com/12787927/142046510-6addb70a-f26d-4a70-8071-315b5077bc15.png)
