### ISSUE TITLE
Link resgistro como Tienda

### ISSUE THREAD

**Issue by yhau1989** [jaimeni/front-solocarro#33]
Cuando le doy click al link de registro como tienda me lleva al URL https://next.workshop-garage.tech/registertiendaone y me da error 404

![Screen Shot 2021-11-11 at 22 26 04](https://user-images.githubusercontent.com/12787927/141403907-9caa5e9c-4efb-497e-b826-6cef0b9f38ca.png)
![Screen Shot 2021-11-11 at 22 27 10](https://user-images.githubusercontent.com/12787927/141404011-bc231fc9-c8c1-4031-a9bb-a0dd76e6d85f.png)

**Comment by jaimeni** [comment]
Esto ya esta resuelto.  El registro de tienda agrega una tienda al dashboard.
