### ISSUE TITLE
Enriquecer la seccion de categorias del front (imagenes)

### ISSUE THREAD

**Issue by yhau1989** [jaimeni/front-solocarro#37]
En la sección de categorias de productos en el front los links a la imagenes estan rotos..!!
![Screen Shot 2021-11-11 at 22 59 38](https://user-images.githubusercontent.com/12787927/141407116-e08a9882-f4ed-4411-9856-71a02af30c2f.png)

**Comment by jaimeni** [comment]
Esto esta funcionando bien.  Para las categorias que no tienen fotos, estas estan apuntando a la imagen product default category que esa en el dashboard en Frontend.

![image](https://user-images.githubusercontent.com/74719300/142195765-e9e001e0-919a-415f-a483-d7616fc15a1d.png)
