### ISSUE TITLE
Brand UI tailwind Style (Home)

### ISSUE THREAD

**Issue by yhau1989** [jaimeni/front-solocarro#41]
Sección derecha con stylos tailwind

![Screen Shot 2021-11-11 at 23 21 55](https://user-images.githubusercontent.com/12787927/141409057-31cfb3a3-5b75-4019-84c8-84956dfe6c0e.png)

**Comment by yhau1989** [comment]
@jaimeni 
- Esta sección es estática o se alimenta desde el Dashboard?

**Comment by jaimeni** [comment]
@yhau1989 Esa seccion es estatica.

**Comment by yhau1989** [comment]
Cambios:

- Mas Tamaño al título primario
- menor tamaño y cambio de color a título secundario.

![Screen Shot 2021-11-14 at 23 23 46](https://user-images.githubusercontent.com/12787927/141722164-978f178f-99f4-4b3f-aba0-0f5f376969e9.png)

![Screen Shot 2021-11-14 at 23 24 11](https://user-images.githubusercontent.com/12787927/141722201-92c05278-c485-4581-a23b-2d14cd124230.png)

**Comment by yhau1989** [comment]
pruebas concluidas por Jaiem
