### ISSUE TITLE
Arreglox UX - Vista Detalle Producto

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#43]
Por favor referir al articulo: https://next.workshop-garage.tech/products/4647

- [ ] Agregar opcion de minimizar a aplicacion de carros

En Figma
![image](https://user-images.githubusercontent.com/74719300/141463480-3efde0c3-7d80-4814-9783-6bea699d5873.png)

En Web
![image](https://user-images.githubusercontent.com/74719300/141463524-e02f9d46-4657-430f-9d73-c0d73ee92fda.png)

- [x] Corregir color en caja de detalle productos

En Figma
![image](https://user-images.githubusercontent.com/74719300/141465382-473e27da-c1f7-4327-95ba-c19ee27761b8.png)

En Web
![image](https://user-images.githubusercontent.com/74719300/141465345-24d8185e-6bd7-480a-aed4-1be00860c448.png)

- [x] Cambiar colores de cajas y texto

En Figma
![image](https://user-images.githubusercontent.com/74719300/141466649-3a0e1b38-1ce6-4e15-8eef-67fc995f5017.png)

En Web
![image](https://user-images.githubusercontent.com/74719300/141466697-5e3fa22a-c998-4049-92e4-0cdb74c0fea5.png)

- [ ] Agregar rectangulo mas grueso

En Figma
![image](https://user-images.githubusercontent.com/74719300/141466831-47ae0a26-bb90-4c07-8c68-10138551906a.png)

En Web
![image](https://user-images.githubusercontent.com/74719300/141466873-b83ee2c8-46f5-4c65-801a-74d828547db7.png)

- [x] Mejorar formato en reviews (https://next.workshop-garage.tech/products/4653)

En Figma
![image](https://user-images.githubusercontent.com/74719300/141467347-0cba2c70-dc1c-42bd-9338-a5413c30deb1.png)

En Web
![image](https://user-images.githubusercontent.com/74719300/141467385-ef34368e-89f1-464c-a607-b2cc47b9e7c6.png)

**Comment by yhau1989** [comment]
Como se ve antes del cambio :
![PARACHOQUE marca](https://user-images.githubusercontent.com/12787927/142365166-695a3739-c18a-4917-82b5-363299add724.png)

![Screen Shot 2021-11-18 at 01 38 59](https://user-images.githubusercontent.com/12787927/142365201-cfb883df-b0c3-4559-a47a-cff67ea72198.png)

![PARACHOQUE mobile](https://user-images.githubusercontent.com/12787927/142365335-20d199d7-aedc-4314-9641-53c3f3db52fd.png)

**Comment by yhau1989** [comment]
Después del cambio.

![MUÑON marca CTR](https://user-images.githubusercontent.com/12787927/142365607-5f16bb5b-d57f-49f9-98c0-76da4ff828de.png)

![MUÑON marca CTR](https://user-images.githubusercontent.com/12787927/142365775-c25eb2ee-6aa3-4196-af6c-197563b9bf69.png)

![PARACHOQUE marca](https://user-images.githubusercontent.com/12787927/142365996-ff0b7775-4301-4523-8d87-4b7b5a771677.png)

![PARACHOQUE marca](https://user-images.githubusercontent.com/12787927/142366059-84f733d2-9e8f-47f9-b63f-73ae4733015a.png)

![PARACHOQUE marca](https://user-images.githubusercontent.com/12787927/142366212-7e73fed5-03d1-47a4-8fbe-5e3985b36c5b.png)

**Comment by yhau1989** [comment]
@jaimeni puedo cerrar este issue?
