### ISSUE TITLE
Arreglos UX - Vista Detalle Servicios

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#45]
- [ ] Agregar imagen de fondo

En Figma
![image](https://user-images.githubusercontent.com/74719300/141471216-0dc81d18-d537-4578-bc3e-0d2f968bf03e.png)

En web
![image](https://user-images.githubusercontent.com/74719300/141471246-5de67ae5-8edf-43c4-9b19-3de73606e522.png)

- [ ] Agregar linea separando productos requeridos y productos opcionales
- [ ] Cambiar color de texto y cambiar rectangulo mas grueso

En Figma
![image](https://user-images.githubusercontent.com/74719300/141471373-f79f8ad2-9f66-4afb-851c-d657c7b0e025.png)

En web
![image](https://user-images.githubusercontent.com/74719300/141471419-f70f73bf-548e-45d2-89e2-f5ccde49352d.png)

- [ ] Ajustar el formato de la descripcion del servicio.  La imagen debe ser envuelta y no ocupar una columna por si solo.

En Figma
![image](https://user-images.githubusercontent.com/74719300/141471907-8dc2953f-f789-4c04-ba6c-3bb34ec8f321.png)

En Web
![image](https://user-images.githubusercontent.com/74719300/141471991-2ece8504-ce9e-4bc1-acca-eaeb2760a829.png)

**Comment by yhau1989** [comment]
Como se ve antes del cambio

![Reemplazo de Sui](https://user-images.githubusercontent.com/12787927/142579637-afc50a9f-1692-48d5-add5-ed807416081b.png)

**Comment by yhau1989** [comment]
como se ve después del cambio 

![Reemplazo de Sui](https://user-images.githubusercontent.com/12787927/142579799-4226d66a-0b68-40b3-b63a-26447c947ce7.png)


![Reemplazo de Sui (1)](https://user-images.githubusercontent.com/12787927/142579978-82c24ef9-969b-4158-9455-5cd88907dd84.png)
![Reemplazo de Sui](https://user-images.githubusercontent.com/12787927/142579986-82403a24-aac1-4b0c-b803-3db9a57c024a.png)
