### ISSUE TITLE
Arreglos UX - Vista Carrito

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#48]
Aunque el layout de la web es distinto al de Figma, creo que me gusta mas el de la web porque esta mas abierto el estilo.

- [ ] Cambiar colores de cajas

Figma
![image](https://user-images.githubusercontent.com/74719300/141476173-872a1bd5-cf18-4d6b-8872-3f65272a6b53.png)

Web
![image](https://user-images.githubusercontent.com/74719300/141476215-b2ce1d08-3cb9-40b6-9b63-1dc36cc61087.png)

**Comment by yhau1989** [comment]
Como se ve después de los cambios.

![Titulo Front Sol (2)](https://user-images.githubusercontent.com/12787927/142742183-f67daa20-48ae-43de-b894-1cb6c82843ef.png)

![Titulo Front Sol (1)](https://user-images.githubusercontent.com/12787927/142742186-b57e115f-7bb5-4c7d-9a12-0da0fe7d7b90.png)

![Titulo Front Sol](https://user-images.githubusercontent.com/12787927/142742189-026840fd-adf7-4481-891a-b1acf95f8888.png)

![Titulo Front Sol (3)](https://user-images.githubusercontent.com/12787927/142742181-a7c2c4a3-22f0-4774-a04e-0f00cc0029af.png)

**Comment by yhau1989** [comment]
@jaimeni @ronikode revisar esto please..!! y cerrar el Issues

**Comment by jaimeni** [comment]
@yhau1989 por favor quitar Costo de Tienda

**Comment by yhau1989** [comment]
@Vixx-X  ha tomado estas mejoras para esta sección
