### ISSUE TITLE
Arreglos UX - Vista Checkout

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#49]
- [ ] Cambiar color del texto
- [ ] Cambiar color de cajas

Figma
![image](https://user-images.githubusercontent.com/74719300/141478114-37b308b8-5e33-4d28-ac09-e024f19d33c3.png)

Web
![image](https://user-images.githubusercontent.com/74719300/141478174-e73c9d91-73ae-4512-8380-010f0546d53b.png)

**Comment by yhau1989** [comment]
Como se ve después del cambio.

![Titulo Front Sol (2)](https://user-images.githubusercontent.com/12787927/142744048-4a78a1c7-2337-4c36-a7f8-a88936f96a2e.png)

![Titulo Front Sol](https://user-images.githubusercontent.com/12787927/142744051-4ffe92d7-1b5d-4541-9727-b209e037485d.png)

![Titulo Front Sol (1)](https://user-images.githubusercontent.com/12787927/142744049-cef946b4-eba2-4047-aa7a-7740436c243a.png)

![Titulo Front Sol (3)](https://user-images.githubusercontent.com/12787927/142744045-39eedf19-9f29-4134-8293-26c0e03b9990.png)

**Comment by yhau1989** [comment]
@jaimeni @ronikode revisar esto please..!! y cerrar el Issues

**Comment by jaimeni** [comment]
@yhau1989 por favor quitar Costo de Tienda.  Eso no debe estar en el Figma

**Comment by yhau1989** [comment]
@Vixx-X  cerró este tema y esta completado.
