### ISSUE TITLE
Checkout no permite enviar la orden al backend

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#66]

**Comment by jaimeni** [comment]
@Vixx-X puedes describir el cambio que hiciste para poder cerrar el issue?  Ya se puede enviar la orden al back.

**Comment by Vixx-X** [comment]
El checkout para multivendors requiere de unas propiedades y modelos adicionales que oscarapi no tomaba en cuenta antes de mandar los correos, las solución fue hookear el método de `handle_order_placement`, del OrderPlacementMixin que se customizo para las vistas de django, y utilizarlo en el create del serializer del checkout.
