### ISSUE TITLE
Nuevas Vistas de Mi Garaje

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#78]
Para poder maximizar la vista de Mi Garaje, se ha decidido quitar el menu lateral y tratar de utilizar la vista completa.  

Vista luego de eliminar menu lateral:
![image](https://user-images.githubusercontent.com/74719300/142418720-a854c90b-d0f5-4444-a768-9f1020b6eeeb.png)

**Comment by yhau1989** [comment]
falta un poquito mas afinar el diseño.
