### ISSUE TITLE
Cambiar Vista Mis Ordenes - Lista

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#94]
![image](https://user-images.githubusercontent.com/74719300/142850644-36ab453b-1913-4e4c-b95e-12bfb1ff2430.png)

**Comment by yhau1989** [comment]
Como se ve después del cambio:
![Devoluciones - S (5)](https://user-images.githubusercontent.com/12787927/143538218-d3fa4a7f-08c9-4367-b9b5-555ca9e787d9.png)
![Devoluciones - S (4)](https://user-images.githubusercontent.com/12787927/143538231-0f68b072-7eec-4434-ad68-d6f6ea34af98.png)
![Devoluciones - S (3)](https://user-images.githubusercontent.com/12787927/143538235-f34f01b4-9387-4ef6-8aad-5dde044bd788.png)
![Devoluciones - S (2)](https://user-images.githubusercontent.com/12787927/143538237-de795f1a-8757-40c5-a323-7215ce5c9a6d.png)
![Devoluciones - S (1)](https://user-images.githubusercontent.com/12787927/143538238-5e276db9-5f4a-46d8-8d87-2f16522d9265.png)
![Devoluciones - S](https://user-images.githubusercontent.com/12787927/143538240-e1781706-d3a3-4b23-9a0a-86dfcca6de21.png)

**Comment by yhau1989** [comment]
@jaimeni  para poder mostrar la info como en el figma se debe cambiar un endpoint tal como lo mencioné en la reunión, tal como está ahora solo se ven los detalles en una 2da llamada al api (popup).

Para mostrarlos en en una sola vista yo debería tener todo el detalle de la orden en un solo llamado al api

Los datos de la cada orden que trae ahorita el primer llamado al api son:

```json 

{
  "ID": 64,
  "NUMBER": "225617",
  "BASKET": "HTTPS://STAGE.WORKSHOP-GARAGE.TECH/API/BASKETS/125617/",
  "URL": "HTTPS://STAGE.WORKSHOP-GARAGE.TECH/API/ORDERS/64/",
  "LINES": "HTTPS://STAGE.WORKSHOP-GARAGE.TECH/API/ORDERS/64/LINES/",
  "OWNER": "HTTPS://STAGE.WORKSHOP-GARAGE.TECH/API/USERS/71/",
  "BILLING_ADDRESS": {
    "ID": 49,
    "COUNTRY": "HTTPS://STAGE.WORKSHOP-GARAGE.TECH/API/COUNTRIES/PE/",
    "TITLE": "",
    "FIRST_NAME": "",
    "LAST_NAME": "",
    "LINE1": "AV SAMUEL PILAY ESQUINA.",
    "LINE2": "",
    "LINE3": "",
    "LINE4": "",
    "STATE": "",
    "POSTCODE": "",
    "SEARCH_TEXT": "AV SAMUEL PILAY ESQUINA. REPUBLIC OF PERU"
  },
  "CURRENCY": "USD",
  "TOTAL_INCL_TAX": "0.06",
  "TOTAL_EXCL_TAX": "0.06",
  "SHIPPING_INCL_TAX": "0.00",
  "SHIPPING_EXCL_TAX": "0.00",
  "SHIPPING_ADDRESS": {
    "ID": 63,
    "COUNTRY": "HTTPS://STAGE.WORKSHOP-GARAGE.TECH/API/COUNTRIES/PE/",
    "TITLE": "",
    "FIRST_NAME": "",
    "LAST_NAME": "",
    "LINE1": "AV SAMUEL PILAY ESQUINA.",
    "LINE2": "",
    "LINE3": "",
    "LINE4": "",
    "STATE": "",
    "POSTCODE": "",
    "SEARCH_TEXT": "AV SAMUEL PILAY ESQUINA. REPUBLIC OF PERU",
    "PHONE_NUMBER": "",
    "NOTES": ""
  },
  "SHIPPING_METHOD": "ENVÍO GRATUITO",
  "SHIPPING_CODE": "FREE-SHIPPING",
  "STATUS": "PENDING",
  "EMAIL": "SPILAY@SOFTWAREMONKEY.COM.EC",
  "DATE_PLACED": "2021-11-23T04:26:44.967231-04:00",
  "PAYMENT_URL": "YOU NEED TO IMPLEMENT A VIEW NAMED 'API-PAYMENT' WHICH REDIRECTS TO THE PAYMENT PROVIDER AND SETS UP THE CALLBACKS.",
  "OFFER_DISCOUNTS": [],
  "VOUCHER_DISCOUNTS": [],
  "SURCHARGES": [],
  "REVIEWS": []
}

```
Como podrás ver solo trae la cabecera del pedido pero no el detalle de los ítems del pedido.

**Comment by jaimeni** [comment]
Como conversamos en la reunion de hoy:

- Vamos a mostrar la vista expandida de los productos en las ordenes como hace Amazon.  En caso de que el usuario cliquea ver mas detalles de la orden, se abrira otra vista con mas detalles de la orden
- Va a ver un boton en donde se puede mostrar las ordenes como una lista.  Esto seria para los talleres que tienen muchas ordenes
- El boton de comprar otra vez agrega el producto al carrito.  Si hay un cambio de precio se debe notificar.  El issue 242 en el back se esta revisando si se guarda el precio de la orden del pasado para hacer la comparacion con el precio actual.  
- El boton de Devolver/Reemplazar no se muestra cuando el usuario ha ingresado una devolucion de ese articulo o si ha pasado el plazo de tiempo permitido para permitir la devolucion.  
- El boton de Calificar no se muestra si el usuario ya ha ingresado una calificacion.

**Comment by jaimeni** [comment]
@darwinrq puedes indicarle a Samuel cuales son los endpoints que el tiene que acceder para generar la vista?

**Comment by ronikode** [comment]
@darwinrq , @Vixx-X porque se esta compartiendo la documentacion openApi Swagger, para el endpoint en mencion y de esa forma agilizar la integracion con el front?

**Comment by yhau1989** [comment]
**Se agrega** Componente para cambiar la forma de ver la lista:

![Screen Shot 2021-11-26 at 23 27 47](https://user-images.githubusercontent.com/12787927/143667976-5ed717f9-9967-4e37-8cb8-ef8354ca5df1.png)

**Comment by jaimeni** [comment]
@yhau1989 todavia queda pendiente conectar los botones y agregar la opcion de ver el detalle de la orden completa en otra vista.  Este concepto seria igual al de Amazon en caso que el usuario desee imprimir la factura de la orden.

**Comment by yhau1989** [comment]
**Items de la cada compra**:

@ronikode @Vixx-X 
Viene los datos pero la foto de los productos no, busque deteo del objeto `"compra".lines[i].image` y `compra".lines[i].product.images` y nada


![Screen Shot 2021-11-30 at 00 21 06](https://user-images.githubusercontent.com/12787927/143990461-fe99a628-bf21-4ee1-8680-afa336be1626.png)

**Comment by yhau1989** [comment]
funcionalidad de ingreso de devolución:

![Mis ordenes - So (1)](https://user-images.githubusercontent.com/12787927/144011852-296c2978-8e47-47f3-9b9e-170d3278ef64.png)
![Mis ordenes - So](https://user-images.githubusercontent.com/12787927/144011857-eece901c-04b3-4590-9ef8-9ff1c4b9adb3.png)


![Mis ordenes - So (2)](https://user-images.githubusercontent.com/12787927/144011838-9cd0185d-eef6-4665-aa47-6c2b0cca04f5.png)
![Screen Shot 2021-11-30 at 03 25 23](https://user-images.githubusercontent.com/12787927/144012195-71bef744-0b1f-48d5-aea3-1a8f19c37144.png)

![Screen Shot 2021-11-30 at 03 25 32](https://user-images.githubusercontent.com/12787927/144012189-75b629db-8986-467b-9ece-6cc1781e6237.png)

**Comment by yhau1989** [comment]
Se agregó los cambios para:

- enviar a: `${order.shipping_address.first_name} ${order.shipping_address.last_name}`
- items images: `compra".lines[i].product.images[0]`
