### ISSUE TITLE
Cambiar Vista Devoluciones - Lista

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#95]
![image](https://user-images.githubusercontent.com/74719300/142852648-702b49b2-cd87-4db9-8e55-663f71afbda6.png)

**Comment by darwinrq** [comment]
API: https://stage.workshop-garage.tech/api/tickets/

JSON: 
{
"count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 41,
            "num_ticket": "#00000041",
            "reason": "https://stage.workshop-garage.tech/api/return-reason/2/",
            "order": "https://stage.workshop-garage.tech/api/orders/46/",
            "date_created": "2021-11-10T16:31:51.122941-04:00",
            "comment": "prueba ",
            "status": "PENDING",
            "lines": [
                {
                    "ticket": "https://stage.workshop-garage.tech/api/tickets/41/",
                    "product": "https://stage.workshop-garage.tech/api/products/22/",
                    "quantity": 1,
                    "amount": "29.90"
                }
            ]
        },
        {
            "id": 40,
            "num_ticket": "#00000040",
            "reason": "https://stage.workshop-garage.tech/api/return-reason/6/",
            "order": "https://stage.workshop-garage.tech/api/orders/46/",
            "date_created": "2021-10-29T17:04:57.308702-04:00",
            "comment": "sadasdw",
            "status": "PENDING",
            "lines": [
                {
                    "ticket": "https://stage.workshop-garage.tech/api/tickets/40/",
                    "product": "https://stage.workshop-garage.tech/api/products/78283/",
                    "quantity": 1,
                    "amount": "53.00"
                }
            ]
}

**Comment by yhau1989** [comment]
**Se agrega** Componente para cambiar la forma de ver la lista:

![Screen Shot 2021-11-26 at 23 27 47](https://user-images.githubusercontent.com/12787927/143667976-5ed717f9-9967-4e37-8cb8-ef8354ca5df1.png)


**Se cambia** la vista a esto


![Devoluciones - S](https://user-images.githubusercontent.com/12787927/143667930-88c63371-f3b8-499f-9882-8ee4073d0412.png)

**Consideraciones**:

- Definir mejor el UX y UI de esta pagina en figma
- Definir bien las opciones a mostrar (botones)

**Comment by yhau1989** [comment]
@jaime Para revisar la pantalla ir al url https://next.workshop-garage.tech/account/returns/samo

**Comment by jaimeni** [comment]
@yhau1989 esta pagina es solo para mostrar las devoluciones que ha ingresado el usuario.  Los botones de accion son

- Ver detalle
- Cancelar Devolucion

**Comment by yhau1989** [comment]
@jaimeni @Vixx-X @ronikode @darwinrq  la funcionalidad de cancelar en el api ya está lista, qué método es ???

https://stage.workshop-garage.tech/api/docs/redoc/#tag/tickets

**Comment by yhau1989** [comment]
funcionalidad ver detalle 

![Devoluciones - S](https://user-images.githubusercontent.com/12787927/144011667-9f2ede83-71af-4e89-8734-6c96db571941.png)
![Devolución # 10](https://user-images.githubusercontent.com/12787927/144011684-73269f64-ebf0-44c0-a4d2-12c747fed979.png)

**Comment by jaimeni** [comment]
> @jaimeni @Vixx-X @ronikode @darwinrq la funcionalidad de cancelar en el api ya está lista, qué método es ???
> 
> https://stage.workshop-garage.tech/api/docs/redoc/#tag/tickets

He creado un issue 253 en el back para el boton Cancelar.

**Comment by yhau1989** [comment]
Revisé la documentación y no existe el método para editar ticket. cc/@jaimeni @Vixx-X @ronikode @darwinrq 

![Screen Shot 2021-12-02 at 00 30 57](https://user-images.githubusercontent.com/12787927/144363417-dbea0d7d-1fd2-48e7-a954-ebb9522f8681.png)

**Comment by yhau1989** [comment]
Se crea la funcionalidad de cancelar ticket de devolución, **aun falta mostrar panel de alerta de la acción** 
![Devoluciones - S](https://user-images.githubusercontent.com/12787927/144567293-4057269f-9872-4d5f-b4fd-0770fa2e83bc.png)
