### ISSUE TITLE
Vista - Detalle de Devolucion

### ISSUE THREAD

**Issue by jaimeni** [jaimeni/front-solocarro#98]
![image](https://user-images.githubusercontent.com/74719300/142853596-877394f4-e0b7-4f59-a5a0-0a6daf52cd2c.png)

**Comment by yhau1989** [comment]
@jaimeni el issues [issues95](https://github.com/jaimeni/front-solocarro/issues/95 ) ya resuelve esto

**Comment by jaimeni** [comment]
@yhau1989 he creado el issue 253 en el back para desarrollar esta API
